#!/usr/bin/env python3
"""
Build a static site from MacGyver's reverse specs.

Walks agents/macgyver/mind/expertise/, converts each .md to HTML,
and generates an index page listing all analyzed repos.
"""
import os
import re
from pathlib import Path

import markdown

EXPERTISE_DIR = Path("expertise")
OUTPUT_DIR = Path("_site")

STYLE = """
:root {
    --bg: #ffffff; --fg: #1a1a1a; --link: #0066cc;
    --link-visited: #551a8b; --border: #e0e0e0; --code-bg: #f5f5f5;
    --card-bg: #fafafa;
}
@media (prefers-color-scheme: dark) {
    :root {
        --bg: #1a1a1a; --fg: #e0e0e0; --link: #6db3f2;
        --link-visited: #b794f4; --border: #333; --code-bg: #2d2d2d;
        --card-bg: #222;
    }
}
* { box-sizing: border-box; }
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    line-height: 1.6; max-width: 900px; margin: 0 auto; padding: 2rem;
    background: var(--bg); color: var(--fg);
}
a { color: var(--link); }
a:visited { color: var(--link-visited); }
h1 { border-bottom: 2px solid var(--border); padding-bottom: 0.3em; }
h2, h3 { margin-top: 1.5em; }
code {
    background: var(--code-bg); padding: 0.2em 0.4em;
    border-radius: 3px; font-size: 0.9em;
}
pre { background: var(--code-bg); padding: 1em; border-radius: 5px; overflow-x: auto; }
pre code { background: none; padding: 0; }
.repo-card {
    border: 1px solid var(--border); border-radius: 8px;
    padding: 1em 1.5em; margin: 0.75em 0; background: var(--card-bg);
}
.repo-card h3 { margin: 0 0 0.3em 0; }
.repo-card p { margin: 0; color: #666; font-size: 0.9em; }
.breadcrumb { font-size: 0.9em; margin-bottom: 1em; }
.breadcrumb a { text-decoration: none; }
footer { margin-top: 3em; padding-top: 1em; border-top: 1px solid var(--border);
         font-size: 0.85em; color: #888; }
"""


def extract_title_and_summary(md_text: str) -> tuple[str, str]:
    """Extract the first H1 as title and first paragraph as summary."""
    title = ""
    summary = ""

    for line in md_text.split("\n"):
        if line.startswith("# ") and not title:
            title = line[2:].strip()
        elif line.strip() and not line.startswith("#") and title and not summary:
            summary = line.strip()
            break

    return title, summary


def build_spec_page(md_path: Path, rel_path: str) -> dict:
    """Convert a spec markdown file to HTML. Returns metadata dict."""
    md_text = md_path.read_text("utf-8")
    title, summary = extract_title_and_summary(md_text)

    # Derive owner/repo from path
    parts = rel_path.replace(".md", "").split("/")
    owner = parts[0] if len(parts) > 1 else ""
    repo = parts[1] if len(parts) > 1 else parts[0]
    full_name = f"{owner}/{repo}" if owner else repo

    # Convert markdown to HTML
    md = markdown.Markdown(extensions=["extra", "toc", "fenced_code"])
    body_html = md.convert(md_text)

    page_title = title or full_name
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{page_title} — MacGyver Specs</title>
    <style>{STYLE}</style>
</head>
<body>
    <div class="breadcrumb"><a href="../../index.html">← All Specs</a> / {owner} / {repo}</div>
    {body_html}
    <footer>
        Generated by <a href="https://github.com/ianphil/macgyver">MacGyver</a> —
        an autonomous reverse-spec agent.
        <br>Source: <a href="https://github.com/{full_name}">{full_name}</a>
    </footer>
</body>
</html>"""

    # Write HTML
    out_path = OUTPUT_DIR / rel_path.replace(".md", ".html")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, "utf-8")

    return {
        "full_name": full_name,
        "owner": owner,
        "repo": repo,
        "title": page_title,
        "summary": summary,
        "url": rel_path.replace(".md", ".html"),
    }


def build_index(specs: list[dict]):
    """Generate the index page listing all specs."""
    specs_sorted = sorted(specs, key=lambda s: s["full_name"].lower())

    cards = ""
    for spec in specs_sorted:
        summary_html = f"<p>{spec['summary']}</p>" if spec["summary"] else ""
        cards += f"""
        <div class="repo-card">
            <h3><a href="{spec['url']}">{spec['full_name']}</a></h3>
            {summary_html}
        </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MacGyver — Reverse Specs</title>
    <style>{STYLE}</style>
</head>
<body>
    <h1>🔍 MacGyver — Reverse Specs</h1>
    <p>
        Autonomous reverse-engineered specifications generated by
        <strong>MacGyver</strong>, an AI agent that watches GitHub stars
        and produces product-level specs from source code.
    </p>
    <p><strong>{len(specs)}</strong> repos analyzed.</p>
    {cards}
    <footer>
        Powered by <a href="https://github.com/ianphil/macgyver">MacGyver</a>.
        Star a repo → MacGyver analyzes it → spec appears here.
    </footer>
</body>
</html>"""

    index_path = OUTPUT_DIR / "index.html"
    index_path.write_text(html, "utf-8")
    print(f"Built index with {len(specs)} specs")


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if not EXPERTISE_DIR.exists():
        print(f"No expertise directory found at {EXPERTISE_DIR}")
        build_index([])
        return

    specs = []
    for md_file in sorted(EXPERTISE_DIR.rglob("*.md")):
        rel = str(md_file.relative_to(EXPERTISE_DIR))
        print(f"  Converting {rel}")
        meta = build_spec_page(md_file, rel)
        specs.append(meta)

    build_index(specs)
    print(f"Site built in {OUTPUT_DIR}/")


if __name__ == "__main__":
    main()
